M48
; DRILL file {KiCad (6.0.11)} date Wed Feb 14 19:56:17 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-02-14T19:56:17+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.11)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.700
%
G90
G05
T1
X140.0Y-70.8
X145.0Y-70.8
T2
X104.648Y-106.172
X104.648Y-121.412
X145.288Y-106.172
X145.288Y-121.412
T0
M30
